import ExcelJS from "exceljs";
import { buildParsedRows, type ParsedRow } from "./parse-rows";
import type { ImportRowType } from "@/lib/validations/import";
import {
  parseImportTypeMarker,
  detectImportTypeMismatch,
  importTypeMismatchMessage,
} from "@/lib/constants/user-import";

export type ParseExcelResult = { rows: ParsedRow[] } | { error: string };

// The one place that loads an uploaded .xlsx workbook, strips the
// template's required-field header asterisk, checks the import-type
// marker (falling back to header-shape detection for files with no
// marker), and builds validated rows. Shared by the web browser-upload
// route (/api/users/import/parse) and the mobile file-upload route
// (/api/mobile/me/users/import/validate-file) — a second, drifted copy of
// this logic already caused one bug this session (the " *" required-field
// suffix breaking header-to-field mapping), so there must only ever be one.
export async function parseExcelImportFile(
  buffer: ArrayBuffer,
  importType: ImportRowType
): Promise<ParseExcelResult> {
  try {
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);

    const sheet = workbook.getWorksheet("Data") ?? workbook.worksheets[0];
    if (!sheet) {
      return { error: "Could not find a sheet with data in this Excel file" };
    }

    // Strip the "required field" asterisk the template adds to header text
    // (e.g. "idNumber *") — without this, required columns never match the
    // schema's plain field names and every required field looks "missing".
    const headers: string[] = [];
    sheet.getRow(1).eachCell({ includeEmpty: false }, (cell, colNumber) => {
      headers[colNumber - 1] = String(cell.value ?? "").trim().replace(/\s*\*$/, "");
    });

    // Reject a wrong-template upload up front, as a single clear error —
    // never as per-row noise about columns the file legitimately lacks.
    // Prefer the machine-readable marker on the hidden Lists sheet (present
    // on any file generated by our own template); fall back to header-shape
    // detection for plain CSVs or hand-built files with no such marker.
    const listsSheet = workbook.getWorksheet("Lists");
    const markerType = listsSheet
      ? parseImportTypeMarker(listsSheet.getCell(1, 4).value)
      : null;

    let detectedType: ImportRowType | null = null;
    if (markerType) {
      if (markerType !== importType) detectedType = markerType;
    } else {
      detectedType = detectImportTypeMismatch(headers, importType);
    }

    if (detectedType) {
      return { error: importTypeMismatchMessage(importType, detectedType) };
    }

    const data: Record<string, string>[] = [];
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber === 1) return; // header row, already read above

      const record: Record<string, string> = {};
      let hasValue = false;
      headers.forEach((header, idx) => {
        if (!header) return;
        const value = row.getCell(idx + 1).value;
        const text = value == null ? "" : String(value);
        record[header] = text;
        if (text) hasValue = true;
      });
      if (hasValue) data.push(record);
    });

    const rows = buildParsedRows(data, importType);
    return { rows };
  } catch (err) {
    return {
      error: `Failed to parse Excel file: ${err instanceof Error ? err.message : "Unknown error"}`,
    };
  }
}
