import { NextRequest, NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { requireAdmin } from "@/lib/auth-helpers";
import { buildParsedRows } from "@/lib/imports/parse-rows";
import type { ImportRowType } from "@/lib/validations/import";
import {
  parseImportTypeMarker,
  detectImportTypeMismatch,
  importTypeMismatchMessage,
} from "@/lib/constants/user-import";

export async function POST(req: NextRequest) {
  await requireAdmin();

  const formData = await req.formData();
  const file = formData.get("file");
  const type = formData.get("type");

  if (type !== "faculty" && type !== "student") {
    return NextResponse.json(
      { error: "Invalid import type. Use type=faculty or type=student." },
      { status: 400 }
    );
  }
  if (!file || !(file instanceof File)) {
    return NextResponse.json({ error: "No file provided" }, { status: 400 });
  }

  const importType: ImportRowType = type === "faculty" ? "FACULTY" : "STUDENT_FARMER";

  try {
    const buffer = await file.arrayBuffer();
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);

    const sheet = workbook.getWorksheet("Data") ?? workbook.worksheets[0];
    if (!sheet) {
      return NextResponse.json(
        { error: "Could not find a sheet with data in this Excel file" },
        { status: 400 }
      );
    }

    // Strip the "required field" asterisk the template adds to header text
    // (e.g. "idNumber *") — without this, required columns never match the
    // schema's plain field names and every required field looks "missing".
    const headers: string[] = [];
    sheet.getRow(1).eachCell({ includeEmpty: false }, (cell, colNumber) => {
      headers[colNumber - 1] = String(cell.value ?? "").trim().replace(/\s*\*$/, "");
    });

    // Reject a wrong-template upload up front, as a single clear error —
    // never as per-row noise about columns the file legitimately lacks.
    // Prefer the machine-readable marker on the hidden Lists sheet (present
    // on any file generated by our own template); fall back to header-shape
    // detection for plain CSVs or hand-built files with no such marker.
    const listsSheet = workbook.getWorksheet("Lists");
    const markerType = listsSheet
      ? parseImportTypeMarker(listsSheet.getCell(1, 4).value)
      : null;

    let detectedType: ImportRowType | null = null;
    if (markerType) {
      if (markerType !== importType) detectedType = markerType;
    } else {
      detectedType = detectImportTypeMismatch(headers, importType);
    }

    if (detectedType) {
      return NextResponse.json(
        { error: importTypeMismatchMessage(importType, detectedType) },
        { status: 400 }
      );
    }

    const data: Record<string, string>[] = [];
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber === 1) return; // header row, already read above

      const record: Record<string, string> = {};
      let hasValue = false;
      headers.forEach((header, idx) => {
        if (!header) return;
        const value = row.getCell(idx + 1).value;
        const text = value == null ? "" : String(value);
        record[header] = text;
        if (text) hasValue = true;
      });
      if (hasValue) data.push(record);
    });

    const rows = buildParsedRows(data, importType);
    return NextResponse.json(rows);
  } catch (err) {
    return NextResponse.json(
      {
        error: `Failed to parse Excel file: ${err instanceof Error ? err.message : "Unknown error"}`,
      },
      { status: 400 }
    );
  }
}
